### ISSUE TITLE
function handler = index.handler not found

### ISSUE THREAD

**Issue by bear-ei** [midwayjs/midway-faas#114]
v 0.2.66

npm test

```
Testing all *.test.js/ts...


  /test/index.test.ts
    1) invoke


  0 passing (3s)
  1 failing

  1) /test/index.test.ts
       invoke:
     Error: function handler = index.handler not found
      at AsyncFunction.<anonymous> (node_modules/@midwayjs/faas/src/starter.ts:144:13)
      at invokeHandlerWrapper (node_modules/@midwayjs/serverless-fc-starter/src/runtime.ts:55:22)
      at FCRuntime.invokeHandlerWrapper (node_modules/@midwayjs/runtime-engine/src/lightRuntime.ts:19:28)
      [use `--full-trace` to display the full stack trace]

```

**Comment by czy88840616** [comment]
看上去像是因为beta产生了多个ioc容器，我看看包。

**Comment by czy88840616** [comment]
看起来没有问题，更新一下依赖，注意先删一下 package-lock.json，防止锁版本。

**Comment by tsui66** [comment]
这种错一般是 ` @midwayjs/faas-cli`  和函数版本不一样; 建议检查版本号或  `npm install --registry=https://registry.npm.taobao.org @midwayjs/faas-cli -g`;
